### ISSUE TITLE
Complete JSON representation of a mvt file

### ISSUE THREAD

**Issue by aleonnet** [saigontek/dart-vector-tile#15]
Hi @bahung1221 ,
Thank you for the packge.

1. How can we get a result similar to this JSON? A complete JSON representation of a mvt file.

2. Will it work with tiles from https://project-osrm.org/docs/v5.24.0/api/#tile-service?

...
Sample VectorTile (raw) decoded (as JSON)

{
  "layers": [
    {
      "name": "poi",
      "features": {
        "id": 31162829580,
        "tags": [
          0,
          0,
          1,
          1
        ],
        "type": "POINT",
        "geometry": [
          9,
          8058,
          1562
        ]
      },
      "keys": [
        "render_height",
        "name"
      ],
      "values": [
        {
          "intValue": 65
        },
        {
          "stringValue": "basketball"
        }
      ],
      "extent": 4096,
      "version": 2
    }
  ]
}

...
3. Can it be done with any similar code like below (python example)?

import mapbox_vector_tile
import json

with open('0.mvt', 'rb') as f:
    data = f.read()
decoded_data = mapbox_vector_tile.decode(data)

sorted_data = json.dumps(decoded_data, indent=4, sort_keys=True)

with open('0.json', 'w') as f:
f.write(sorted_data)

**Comment by bahung1221** [comment]
1. How can we get a result similar to this JSON? A complete JSON representation of a mvt file.

You can use below code to get the result (just use mvt file instead of pdf). But it will return an VectorTile object, not an json string, currently there is no toJson method implemented for the VectorTile class :D You can convert it by yourself: https://docs.flutter.dev/data-and-backend/serialization/json

```dart
final tileData = await File('../data/sample-12-3262-1923.pbf').readAsBytes();
final tile = await VectorTile.fromBytes(bytes: tileData);
```

2. Will it work with tiles from https://project-osrm.org/docs/v5.24.0/api/#tile-service?

It should work because this package followed the [Mapbox Vector Tile specification 2.1](https://github.com/mapbox/vector-tile-spec).

3. Can it be done with any similar code like below (python example)?

Yes, same with the question one
